/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.processor.*
import org.example.model.Task

fun main(args: Array<String>) {
    val expression = "5 + 3 * 2 - (5 / 5) + 1 - 4"
    val iterations = if (args.isNotEmpty()) args[0].toIntOrNull() ?: 1 else 1
    println("Evaluating expression '$expression' $iterations times...")
    val tasks = List(iterations) { Task(expression) }
    val startTime = System.nanoTime()
    println("Thread pool:")
    TaskProcessor(ProcessingStrategy.FIXED_THREAD_POOL).submit(tasks).shutdown()
    val endTime = System.nanoTime()
    val durationMs = (endTime - startTime) / 1_000_000.0
    println("Execution time: $durationMs ms")
}
